services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      DB_USER: root
      DB_PWD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: rest_api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile.test
    environment:
      DB_USER: root
      DB_PWD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: rest_api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rest_api
    volumes:
      - db_data:/var/lib/mysql
      - ./share/sql/rest_api.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
