FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir cryptography pytest

COPY src/ ./src/
COPY tests/ ./tests/

ENV DB_USER=root
ENV DB_PWD=root
ENV DB_HOST=db
ENV DB_PORT=3306
ENV DB_NAME=rest_api

CMD ["pytest", "tests/", "-v"]
